modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "finalfrontier"
version = "${version}"
displayName = "Create: Final Frontier"
authors = "Me!"
description = '''
A Minecraft Create mod addon focusing on semi-realistic space travel
'''
logoFile = "icon.png"

[[dependencies.finalfrontier]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.finalfrontier]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.finalfrontier]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"